In [5]:
import numpy as np
a=np.random.randint(30,99,20)
a

array([80, 68, 33, 45, 95, 70, 58, 46, 53, 97, 73, 58, 83, 55, 56, 38, 83,
       80, 63, 48])

In [11]:
a[-1]


48

In [15]:
a[10]

73

In [17]:
import numpy as np

In [5]:
import numpy as np
b=np.random.randint(20,80,(8,9))
b

array([[76, 39, 74, 63, 78, 72, 34, 72, 57],
       [70, 43, 30, 68, 50, 47, 74, 65, 30],
       [77, 27, 48, 23, 76, 29, 21, 53, 72],
       [50, 64, 32, 23, 39, 47, 23, 49, 24],
       [41, 66, 35, 68, 38, 48, 20, 53, 24],
       [38, 72, 68, 54, 75, 53, 32, 73, 34],
       [38, 73, 35, 73, 27, 38, 24, 44, 36],
       [33, 74, 65, 45, 39, 48, 65, 61, 32]])

In [7]:
b.shape

(8, 9)

In [9]:
b.ndim

2

In [11]:
b[7,0]

33

array[row_start: row_end : row_start , col_start: col_step]

In [37]:
b[0:8]

array([[76, 39, 74, 63, 78, 72, 34, 72, 57],
       [70, 43, 30, 68, 50, 47, 74, 65, 30],
       [77, 27, 48, 23, 76, 29, 21, 53, 72],
       [50, 64, 32, 23, 39, 47, 23, 49, 24],
       [41, 66, 35, 68, 38, 48, 20, 53, 24],
       [38, 72, 68, 54, 75, 53, 32, 73, 34],
       [38, 73, 35, 73, 27, 38, 24, 44, 36],
       [33, 74, 65, 45, 39, 48, 65, 61, 32]])

In [39]:
b[1:7]

array([[70, 43, 30, 68, 50, 47, 74, 65, 30],
       [77, 27, 48, 23, 76, 29, 21, 53, 72],
       [50, 64, 32, 23, 39, 47, 23, 49, 24],
       [41, 66, 35, 68, 38, 48, 20, 53, 24],
       [38, 72, 68, 54, 75, 53, 32, 73, 34],
       [38, 73, 35, 73, 27, 38, 24, 44, 36]])

In [41]:
b[2:6]

array([[77, 27, 48, 23, 76, 29, 21, 53, 72],
       [50, 64, 32, 23, 39, 47, 23, 49, 24],
       [41, 66, 35, 68, 38, 48, 20, 53, 24],
       [38, 72, 68, 54, 75, 53, 32, 73, 34]])

In [43]:
b[1:5,1:6]

array([[43, 30, 68, 50, 47],
       [27, 48, 23, 76, 29],
       [64, 32, 23, 39, 47],
       [66, 35, 68, 38, 48]])

In [45]:
b[3:8]

array([[50, 64, 32, 23, 39, 47, 23, 49, 24],
       [41, 66, 35, 68, 38, 48, 20, 53, 24],
       [38, 72, 68, 54, 75, 53, 32, 73, 34],
       [38, 73, 35, 73, 27, 38, 24, 44, 36],
       [33, 74, 65, 45, 39, 48, 65, 61, 32]])

In [47]:
b[3:8,2:8]

array([[32, 23, 39, 47, 23, 49],
       [35, 68, 38, 48, 20, 53],
       [68, 54, 75, 53, 32, 73],
       [35, 73, 27, 38, 24, 44],
       [65, 45, 39, 48, 65, 61]])

In [55]:
import pandas as pd

In [61]:
np.array(t)

array([ 4,  7,  2,  9,  7,  3, 90, 50])

In [71]:
import pandas as pd
pd.Series(t)

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [69]:
t=[[4,7],[2,9],[7,3],[90,50]]
t

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [84]:
t=[[4,7],[2,9],[7,3],[90,50]]
t

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [86]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [100]:
t=[[4,7],[2,9],[7,3],[90,50]]
t

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [114]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [116]:
df.columns

Index(['name', 'sub'], dtype='object')

In [118]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int64

In [120]:
df['sub'].min()

3

In [122]:
df['sub'].max()

50

In [124]:
df['sub'].quantile(0.75)

19.25

In [126]:
df['sub'].mode()

0     3
1     7
2     9
3    50
Name: sub, dtype: int64

In [ ]:
df['sub'].me()